services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  cloudapi:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./CloudApi/Dockerfile
    container_name: cloudapi
    depends_on:
      sqlserver:
        condition: service_healthy   # ⬅ SQL Server эрүүл болтол CloudApi эхлэхгүй
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    ports:
      - "5001:5001"
      
volumes:
    sql_data:
